### ISSUE TITLE
Не работает `Canot load data`

### ISSUE THREAD

**Issue by akokarev** [elmot/turku#3]
`Failed to load resource: the server responded with a status of 404 ()`
[URL load 404](https://spreadsheets.google.com/feeds/cells/1JweHWyLI30MkZiGh1xpzDPynE9zehxQ3tuhZukCFzZE/od6/public/basic?alt=json-in-script&callback=GSDS._a1.loaded)
The Sheets v3 API has been turned down. Further information can be found at: https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api

**Comment by elmot** [comment]
yeah, unfortunately this app won't work anymore. And I am not gonna develop or fix  it further.
